machinezone/IXWebSocket

- ixwebsocket/IXWebSocketHandshake.cpp
Hi, this is a quick fix of this problem. I've create a new [Issue](https://github.com/machinezone/IXWebSocket/issues/9#issue-399222657) at your repo. Hope it helps.
> Fix missing "Upgrade" header error

- CMakeLists.txt
- ws/CMakeLists.txt
Moved to the ixwebsocket to fix linking errors on mac and ios if TLS is enabled
> move security framework linking to ixwebsocket

- ixwebsocket/IXWebSocketTransport.cpp
- ixwebsocket/IXWebSocketTransport.h
- Use constants for ping timeout instead `(1011, "Ping Timeout")`
- Change type of close codes from `int` to `uint16_t`
> Ping timeout use constant

- CMakeLists.txt
On my PC with 4 cores iwx builds for Windows:
* Without `/MP` - 19 sec
* With `/MP` - 12 sec
> Speedup build for Windows

- ixwebsocket/IXNetSystem.cpp
- test/CMakeLists.txt
- test/IXUrlParserTest.cpp
On test case fails on Windows:
```
IXWebSocket\test\IXUrlParserTest.cpp(95): FAILED:
due to unexpected exception with message:
regex_error(error_complexity): The complexity of an attempted match against a
regular expression exceeded a pre-set level.
```
It fails on my real url:
`ws://127.0.0.1:7350/ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NTcxNzAwNzIsInVpZCI6ImMwZmZjOGE1LTk4OTktNDAwYi1hNGU5LTJjNWM3NjFmNWQxZiIsInVzbiI6InN2YmhOdlNJSmEifQ.5L8BUbpTA4XAHlSrdwhIVlrlIpRtjExepim7Yh5eEO4&status=true&format=protobuf`
Good joke about regex:
Some people, when confronted with a problem, think "I know, I'll use regular expressions." Now they have two problems.
:smile:
> added tests for IXUrlParser

- ixwebsocket/IXSocket.cpp
- ixwebsocket/IXSocket.h
- ixwebsocket/IXWebSocket.cpp
- ixwebsocket/IXWebSocket.h
- ixwebsocket/IXWebSocketTransport.cpp
- ixwebsocket/IXWebSocketTransport.h
- test/IXWebSocketPingTest.cpp
- test/IXWebSocketPingTimeoutTest.cpp
- test/IXWebSocketTestConnectionDisconnection.cpp
- Fix ping timeout
- Fix an issue about callback/code read from remote.
When we close the connection using close(code, reason...), a CLOSE frame is sent to the remote, and then right after we really close the socket connection. On the remote side, the CLOSE frame data are read, then the connection is immediately closed so the close callback is called with 1006 / Abnormal close instead of the values of the CLOSE frame, because these data are not processed in the dispatch yet. The fix is to close the connection, set that we need to read the buffer, and if nothing triggered a CLOSED state with the data read, then call the callback with 1006 / Abnormal close
> fix ping, fix send frame close

- test/IXWebSocketTestConnectionDisconnection.cpp
On Linux with GCC there are TSAN errors, the data race seems to happen the first time the thread has enough time to successfully connect (after handshake). After the successful, it's ok, and before each attempt stopped before success, it's ok too. The index where the change occurs depends on the running computer, ie on Travis it's Run 3, on mine it's Run 8
We could reduce the test loop to this too:
```
SECTION("Try to connect to invalid servers.")
{
IXWebSocketTestConnectionDisconnection chatA;
// not enough time to connect
chatA.start(WEBSOCKET_DOT_ORG_URL);
ix::msleep(7*50);
chatA.stop();
// enough time to connect
chatA.start(WEBSOCKET_DOT_ORG_URL);
ix::msleep(8*50);
chatA.stop();
}
```
the error will appear
> Fail test GCC TSAN

- ixwebsocket/IXWebSocket.cpp
- ixwebsocket/IXWebSocket.h
- ixwebsocket/IXWebSocketErrorInfo.h
- test/IXWebSocketTestConnectionDisconnection.cpp
It crashes when `createSocket` fails to create socket on Windows because no SSL support.
Would be good to simulate error when creating socket.
@bsergean how to do that?
> Fix crash during closing on Windows

- CMakeLists.txt
- ixwebsocket/IXSocketFactory.cpp
- ixwebsocket/IXSocketFactory.h
- ixwebsocket/IXSocketOpenSSL.cpp
- ixwebsocket/IXSocketOpenSSL.h
- ixwebsocket/IXSocketTLSOptions.cpp
- ixwebsocket/IXSocketTLSOptions.h
- ixwebsocket/IXWebSocket.cpp
- ixwebsocket/IXWebSocket.h
- ixwebsocket/IXWebSocketTransport.cpp
- ixwebsocket/IXWebSocketTransport.h
This adds a `SocketTLSOptions` type that can be set on clients and servers to configure the certificate used, as well as peer verification options.
> WIP: support configurable certificates/keys, and root trust CAs

- ixwebsocket/IXSocketFactory.cpp
- ixwebsocket/IXWebSocketTransport.cpp
1) IXWebSocketTransport: BUG: int type has no warranty of number of bits. It depends on compiler and architecture. In my system (64 bit) is 32 bit.
1 << 63 is bad idea in this case because the final number is 0 by overflow.
The symptom observed is that the server can't receive messages.
2) IXSocketFactory: Compilation Warning: Variable not in use.
> Compile bug

- README.md
- docs/build.md
- docs/cobra.md
- docs/design.md
- docs/index.md
- docs/usage.md
- docs/ws.md
This is just a meta PR. I added some clarifications on the conan reference version, fixed some typos and accidental language mixes, and repaired a broken URL in README.md.
Ended up doing this in the browser for some reason and made as a result ended up with 8 commits instead of one, so feel free to squash the commits into a single one if you merge this PR.
> Meta: documentation fixes 

- ixwebsocket/IXSelectInterruptFactory.cpp
- ixwebsocket/IXSocketFactory.cpp
Including local headers to avoid confusion with possible Vcpkg installation.
> Fixed build error with vcpkg installed.

- docs/build.md
The PR to Conan Center has been merged \o/ 
This covers a tiny bit on the migration from the old Bintray remote, as well as the package references (it's version-dependent because of updates in 1.21.0).
> Doc update for Conan

- ixwebsocket/IXWebSocketServer.cpp
`IXWebsocketServer.cpp` has a `logInfo()` call, which reports when `handleConnect()` is finished.     There's no way to turn it off, so it makes the server noisy in normal use.
I'm not sure why it is in there, it's the only thing being logged.   So this PR simply removes it.
(Thanks for the nice library!)
> Make WebsocketServer silent: Remove 'handleConnect() done' info message

- ixwebsocket/IXSocketMbedTLS.cpp
- ixwebsocket/IXSocketOpenSSL.cpp
- ixwebsocket/IXSocketOpenSSL.h
- ixwebsocket/IXSocketTLSOptions.cpp
- ixwebsocket/IXSocketTLSOptions.h
Heyo,
I don't think this is ready to merge, but it's at a point where I'd like some feedback on the API design. I feel good about the implementation in IXSocketOpenSSL, but there isn't really a clean way to specify a string for root CAs via SocketTLSOptions.
I've implemented a quick API on SocketTLSOptions so I can test, but I don't think it's the right way to specify a string of certs. Let me know what you think is the ideal way to specify a string cert in SocketTLSOptions and I can implement and update this PR.
Max
> Implement API for adding custom roots via a string

- ixwebsocket/IXWebSocketHandshake.cpp
Client code:
...
ix::WebSocketHttpHeaders headers {
{"Cookie", "ABC"}
};
...
Expected header string on server:
"Cookie: ABC"
Resulted header string on server:
"Cookie: BC"
Solution:
The easy way I found to solve the problem is to add a space where extra headers are set before sended to server.
> Bug on setting extra headers. Now it loses the first string character.

- CMakeLists.txt
Enable the package to be more readily packageable as a system-wide
install or as a third-party dependency to another CMake-base project
This does not change CMake version requirements AFAICT.
Also in case of USE_TLS && OpenSSL it includes(FindOpenSSL) instead of manually calling find_package() etc...
> cmake: add export() and install(EXPORT) for easier packageability

- ixwebsocket/IXHttpClient.cpp
- ixwebsocket/IXHttpClient.h
Discord uses http PATCH for things like message edit which require a body. so i added patch.
Further i know apis also allowing/requiring bodies on other methods such as DELETE, but rather then just pushing a body on every method. i though adding a property to enforce it would be a better approach.
> add PATCH and add option to enforce a http request body write

- CMakeLists.txt
Move the fPIC-option (`CMAKE_POSITION_INDEPENDENT_CODE`) to the top of the CMakeLists, otherwise it will still give the following error when linking against `libixwebsocket.a` (with `-lixwebsocket`) on linux (gcc):
> `/usr/bin/ld: /usr/local/lib/libixwebsocket.a(IXHttpClient.cpp.o): relocation R_X86_64_PC32 against symbol '_ZN2ix10HttpClient3runEv' can not be used when making a shared object; recompile with -fPIC`
> Move the fPIC option to the top of the CMakeLists

- docs/build.md
Adds linking instructions for cmake when using vcpkg
> Extend vcpkg docs

- ixwebsocket/IXUrlParser.cpp
A change introducing std::atoi to IXUrlParser broke support for clang 5 and earlier. See conan-io/conan-center-index#1688. This can be fixed by including `<cstdlib>`. `<cstring>` only contains the relevant functions with Clang 6 and up. Feel free to mess around with the compiler version on Godbolt. The first link (Clang 5, no cstdlib) starts compiling on Clang 6 and up.
Clang 5, no cstdlib: https://godbolt.org/z/9pNAd6
Clang 5, cstdlib: https://godbolt.org/z/qSNt-Z
> Re-enable support for clang 5 and earlier

- CMakeLists.txt
Hi, I found your lib quite useful, but it did not support cmake `find_package`, and it was not convenient to use in my project.
so I add the cmake find config support, so now we can just use your lib like this:
```cmake
find_package(ixwebsocket REQUIRED)
target_link_libraries(mylib PUBLIC ixwebsocket::ixwebsocket)
```
> feat: add cmake find config support

- README.md
The libDiscordBot library is now in a useable state, so I've replaced the WIP text with the actual description of the library.
> Updated libDiscordBot description

- ixwebsocket/IXHttp.cpp
- ixwebsocket/IXHttp.h
- test/IXHttpServerTest.cpp
PR prompted from my question #243 
Simply reads the request's body into a std::string if the Content-Length header was set.
> Read body in parseRequest for HttpServer

- docs/usage.md
- ixbots/ixbots/IXCobraToSentryBot.cpp
- ixwebsocket/IXHttp.cpp
- ixwebsocket/IXHttp.h
- test/IXHttpServerTest.cpp
- ws/ws.cpp
I think it feels odd/inconsistent using the name `payload` in `ix::HttpResponse`, especially when the name `body` is used in `ix::HttpRequest`. 
Would renaming this be OK?
> Rename HttpResponse's payload to body

- ixwebsocket/IXHttp.h
- ixwebsocket/IXHttpClient.cpp
I was running into linker errors when I would disable zlib and try to use the HTTP client. After I looked at them, it looked like it was trying to use zlib to compress requests (only when args->compress was set), this caused linker errors.
I fixed them by adding `#ifdef IXWEBSOCKET_USE_ZLIB` before the if statements and also where you define the `compress` and `compressRequest` fields in the `ix::HttpRequestArgs` struct since they won't be used without zlib.
I tried to follow the same commit message format that I saw you use, in this commit.
> Fix an issue with disabling zlib and getting linker errors from the http client.

- ixwebsocket/IXSocketOpenSSL.cpp
**Error description:**
When using an `IXWebSocket` with the default SSL config, the server certificate is not checked. This can be reproduced by setting your system clock to a date that is outside of the certificates begin/end date. The `IXWebSocket` (specifically `IXSocketOpenSSL`) will still happily connect to it. The OpenSSL version used is 0x1010107fL (1.1.1g).
**Fix:**
Always set `SSL_VERIFY_PEER`, unless `_tlsOptions.isPeerVerifyDisabled()` returns `true`.
**Caveat:**
I don't know if this routine is also used for server sockets. In that case there needs to be a special case, because the `IXWebSocketServer` validating a client certificate is probably not desired. Is this a problem?
> Always make OpenSSL verify the peer certificate

- docs/usage.md
The syntax of the WebSocketServer example was invalid. Not sure if it's perfect, but at least it compiles and runs.
> Fixed example code for the new API of IXWebSocketServer

- ixwebsocket/IXWebSocket.cpp
- ixwebsocket/IXWebSocketMessage.h
Binding `WebSocketMessage` to a temporary message argument can create undefined behavior. This MR introduces a deleted constructor overload to "absorb" cases where string arguments are temporaries and fixes unsafe calls that were "exposed" by the deleted constructor.
> Fix unsafe calls and safeguard WebSocketMessage

- ixwebsocket/IXHttpClient.cpp
The logic for preventing these duplicate headers was flawed. It was checking the empty response's headers rather than the headers specified in the request.
> Avoid duplicate Accept and User-Agent headers

- ixwebsocket/IXWebSocket.cpp
- ixwebsocket/IXWebSocket.h
- ixwebsocket/IXWebSocketMessage.h
- ixwebsocket/IXWebSocketPerMessageDeflateOptions.cpp
- ixwebsocket/IXWebSocketPerMessageDeflateOptions.h
Motivation for this MR #292 
The antipattern of returning references to mutex protected members was removed. Since a caller can hold the reference it would make all class level locking meaningless.
Instead values are returned. The IXWebSocketPerMessageDeflateOptions class was shrunk by 7 bytes (1 padding + 2*3) after changing the int members to the used uint8_t; side effects of that were handled.
An inefficient "string -> int" was replaced by standard library. As seen here http://coliru.stacked-crooked.com/a/46b5990bafb9c626 this gives an order of magnitude better performance.
> Avoid returning references that are mutex protected

- CMakeLists.txt
This PR uses GNUInstallDirs to determine the correct installation includedir/libdir for libraries and headers in CMake.
Tested successfully unter Gentoo Linux, but should work on all other Linux distributions as well, since it's just a standard installation procedure used by many other projects.
Fixes #317.
Signed-off-by: NexAdn <git@nexadn.de>
> Use GNUInstallDirs in cmake

- ixwebsocket/IXNetSystem.cpp
- ixwebsocket/IXNetSystem.h
closes #324
i dug a little deeper and found [why](https://github.com/mingw-w64/mingw-w64/blob/564d8771316bc1836c5e35dae16a5f87467eb310/mingw-w64-headers/include/winsock2.h#L1116) pollfd wasnt being defined, so hopefully this should take care of all situations
> fix compilation under mingw64

- docs/usage.md
Update to documentation. I tried to use this example code and it wouldn't compile; looks like there's a mistake in the name of a field.
> Fix errors in example code.

- docs/usage.md
- ixwebsocket/IXHttp.h
- ixwebsocket/IXHttpClient.cpp
- test/IXHttpClientTest.cpp
Usage:
```cpp
auto args = this->httpClient.createRequest(url, method);
httpClient.performRequest(args, ...);
[...]
// Oops, we don't actually want to complete the request!
args->cancel = true;
```
> Allow to cancel asynchronous HTTP requests

- ixwebsocket/IXNetSystem.h
- ixwebsocket/IXSetThreadName.cpp
- ixwebsocket/IXSocket.h
- ixwebsocket/IXSocketOpenSSL.cpp
- ixwebsocket/IXUdpSocket.h
Hello.
Sorry my English - not native for me.
I'm build this project on ubuntu for windows system with
`svost@svost-VirtualBox:~/src/tmp/IXWebSocket$ x86_64-w64-mingw32-g++ -v
Thread model: posix
gcc version 9.3-posix 20200320 (GCC)`
step 1 build static openssl `CROSS_COMPILE="x86_64-w64-mingw32-" ./Configure mingw64 no-asm no-shared --prefix=/usr/x86_64-w64-mingw32`
step 2 build library `svost@svost-VirtualBox:~/src/tmp$ cmake -DOPENSSL_ROOT_DIR=../openssl-1.1.1m -DWIN32=1 -DMINGW=1 -DWindows=1 -DUSE_ZLIB=0 -DUSE_TLS=1 -DUSE_OPEN_SSL=1 ..`
step 3 build main.cpp and it works `svost@svost-VirtualBox:~/src/tmp$ x86_64-w64-mingw32-g++ --std=c++11 main.cpp -lixwebsocket -I . -L ./build -L ./openssl-1.1.1m -static -static -l kernel32 -l user32 -l gdi32 -l comdlg32 -l winspool -l winmm -l …
> Improved compatibility - less painly mingw crossbuild

- ixwebsocket/IXNetSystem.h
See https://en.cppreference.com/w/cpp/header/cerrno for additional details. Some of used constants are defined in this header.
Inclusion is necessary to avoid these errors:
```
/home/user/IXWebSocket/ixwebsocket/IXNetSystem.cpp:189:30: error: use of undeclared identifier 'EAFNOSUPPORT'
default: errno = EAFNOSUPPORT; return 0;
^
/home/user/IXWebSocket/ixwebsocket/IXNetSystem.cpp:191:17: error: use of undeclared identifier 'ENOSPC'
errno = ENOSPC;
^
/home/user/IXWebSocket/ixwebsocket/IXNetSystem.cpp:175:25: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long long') to 'int' [-Wshorten-64-to-32]
j = strspn(buf + i, ":0");
~ ^~~~~~~~~~~~~~~~~~~~~
/home/user/IXWebSocket/ixwebsocket/IXNetSystem.cpp:234:21: error: use of undeclared identifier 'EAFNOSUPPORT'
errno = …
```
> Include <cerrno> to provide standard error constants

- CMakeLists.txt
Fix #335
https://cmake.org/cmake/help/latest/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html
> Export symbols into .def files for MSVC

- ixwebsocket/IXSocketTLSOptions.cpp
- ixwebsocket/IXWebSocketPerMessageDeflateOptions.cpp
If the per message compression is active the websocket client sends an illegal header to the server.
Instead of
`... ; server_max_window_bits=15; client_max_window_bits=15`
the client sends
? ...; server_max_window_bits=\xf; client-max_window_bits=\xf`
This is caused by using uint8_t that is interpreted as character instead of a number when building the headers.
This PR fixes this bug by casting the `uint8_t` to an `int` when building the headers.
> Fix #340 "HTTP/1.1 400 Illegal character CNTL=0xf"

- CMakeLists.txt
- ixwebsocket/IXNetSystem.cpp
- ixwebsocket/IXNetSystem.h
- ixwebsocket/IXSelectInterrupt.cpp
- ixwebsocket/IXSelectInterrupt.h
- ixwebsocket/IXSelectInterruptEvent.cpp
- ixwebsocket/IXSelectInterruptEvent.h
- ixwebsocket/IXSelectInterruptFactory.cpp
- ixwebsocket/IXSocket.cpp
- ixwebsocket/IXSocket.h
- ixwebsocket/IXSocketConnect.cpp
- ixwebsocket/IXWebSocketTransport.cpp
This PR implements a poll() function that uses WSAEventSelect, WSAWaitForMultipleEvents and WSAEnumNetworkEvents instead of select() under Windows. With the additional SelectInterruptEvent class the Socket::wakeUpFromPoll() method can now wake up the background thread and signal the "SendRequest" and "CloseRequest". Neither the first nor the last thing happend under Windows. Wake up was not possible and requests weren't processed because there was no wake up pipe with the request-value.
Details:
The ix::poll() function now takes an additional `void** event` parameter that is set to `nullptr` when the function returns if the event wasn't signaled. For non-Windows platforms the `event` parameter is always `nullptr`. If no "event" is specified the old `select` implementation is used (There …
> Win wsa select event

- ixwebsocket/IXSelectInterruptEvent.cpp
This PR adds the missing `#include <algorithm>` for IXSelectInterruptEvent.cpp file when compiling under gcc (9.3.0).
gcc (9.3.0) fails to compile with an unknown function std::find() because it was missing the `#include <algorithm>` that seams to be included with other headers on other compiler platforms.
> Fixed missing header for gcc (9.3.0) compilation

- CMakeLists.txt
- docs/usage.md
- ixwebsocket/IXWebSocket.cpp
- ixwebsocket/IXWebSocket.h
- ixwebsocket/IXWebSocketPerMessageDeflate.cpp
- ixwebsocket/IXWebSocketPerMessageDeflate.h
- ixwebsocket/IXWebSocketPerMessageDeflateCodec.cpp
- ixwebsocket/IXWebSocketPerMessageDeflateCodec.h
- ixwebsocket/IXWebSocketSendData.h
- ixwebsocket/IXWebSocketTransport.cpp
- ixwebsocket/IXWebSocketTransport.h
This PR introduces a IXWebSocketSendData class that makes it possible to not only send std::string but also std::vector<char/uint8_t> and char* without copying them to a std::string first. With this the memory usage can be reduced if the data isn't already a std::string.
It also adds a sendUtf8Text() method that doesn't check for invalid UTF-8 characters. The caller must guarantee that the string only contains valid UTF-8 characters. This helps to reduce CPU usage for large strings where the caller already knows that it is valid UTF-8.
> Introduction of IXWebSocketSendData

- CMakeLists.txt
Hello, many thanks for your great library
I'm using it with FetchContent and it's working fine but I can only refer to your library with ixwebsocket while on an install based configuration (using `find_package`) the library is accessible with `ixwebsocket::ixwebsocket`.
This PR allows to use `ixwebsocket::ixwebsocket` inn both cases
> Add an alias for ixwebsocket

- docs/usage.md
- ixwebsocket/IXHttp.cpp
- ixwebsocket/IXHttp.h
- ixwebsocket/IXHttpClient.cpp
- ixwebsocket/IXProgressCallback.h
- ixwebsocket/IXSocket.cpp
- ixwebsocket/IXSocket.h
- test/IXHttpClientTest.cpp
This change adds onChunkCallback to the request. If defined it will be called repeatedly with the incoming data. This allows to process data on the go or write it to disk instead of accumulating the data in memory.
> Add support for streaming transfers

- ixwebsocket/IXNetSystem.cpp
- ixwebsocket/IXSocket.h
- ixwebsocket/IXUdpSocket.h
Hi,
Thanks for this nice library.
Using `msys2 github workflow` msys2/setup-msys2@v2 Clang64 and MINGW32(#352) builds are failling.
These PR fix compilation for this workflow. (tests have not been run)
> Fix for MINGW32 and clang on windows (#352)

- CMakeLists.txt
- ixwebsocket/IXDNSLookup.h
- ixwebsocket/IXHttpClient.h
- ixwebsocket/IXHttpServer.h
- ixwebsocket/IXSocketServer.h
- ixwebsocket/IXWebSocketCloseConstants.h
- ixwebsocket/IXWebSocketServer.h
- ixwebsocket/IXWebsocketExport.h
CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS from f53b2f8 doesn't export static class members, so when building ws.exe linked against shared ixwebsocket library VS displays errors 'LNK2019 symbol not found'
the solution:
define IXWEBSOCKET_EXPORT to __declspec(dllexport) when building windows dynamic library, to __declspec(dllimport) when using it, to nothing in other cases (static or not windows). then apply this define to all the static members in all .h files
like `IXWEBSOCKET_EXPORT const static bool kDefaultEnablePong;`
> Export static symbols when building ws with shared library

- CMakeLists.txt
- ixwebsocket-config.cmake.in
Fix https://github.com/machinezone/IXWebSocket/issues/382
Add ixwebsocket-config.cmake and ixwebsocket-targets.cmake.
Verified with vcpkg, the target ZLIB::ZLIB could be found successfully.
> vcpkg zlib dep fix

- CMakeLists.txt
- ixwebsocket/IXBase64.h
- ixwebsocket/IXWebSocketHandshake.cpp
The generated header only "looked like" Base64, but if the other side actually tried to decode it as such, it could fail. This change fixes that to always generate a valid Base64 value.
This adds external code to do the base64 encoding. Not sure where you'd like to locate that inside the source tree, happy to change that to a different location, just let me know.
> Fix `Sec-WebSocket-Key` to contain valid Base64.

- docs/build.md
I am really new to CMake and C++ and I am no expert but I think it should say NOTFOUND instead of NOTFOUNS.
(Bit of a side note which has nothing to do with this pull request but I thought I might as well mention, I also installed IXWebSocket using vcpkg and want to use it in a CMake project but IXWEBSOCKET_INCLUDE_DIR and IXWEBSOCKET_LIBRARY are both NOTFOUND)
> Fix spelling mistake in docs

- ixwebsocket/IXHttpServer.cpp
The old version of `IXWebSocket` did not correctly handle the front-end static file type, causing the front-end page rendering to fail.
The browser needs to recognize the `Content-Type` parameter to determine the file type for rendering, so it is necessary to manually declare the `Content-Type` parameter.
> add Content-Type support

- ixwebsocket/IXHttpClient.cpp
- ixwebsocket/IXUrlParser.cpp
- ixwebsocket/IXUrlParser.h
For connection like "http://localhost:8180/" we need send the host name with the port. For more info see https://www.rfc-editor.org/rfc/rfc9110.html#name-host-and-authority
> HTTP should contain port in 'Host' header

- ixwebsocket/IXSocketServer.cpp
- ixwebsocket/IXSocketServer.h
During my tests, I like to start and stop a WebSockets server inside an infinite loop. However, sometimes the loop stops.
I think the problem lies in `_conditionVariableGC`. We use this condition variable to notify the `runGC` thread that something has to be "garbage collected". I think the deadlock happens when we notify the condition variable when the `runGC` is not yet waiting for the condition variable. To prevent this, I use the boolean member `_canContinueGC` to "buffer" the notification. If we want to notify `runGC` while it's not waiting, we can just set `_canContinueGC` to true and `runGC` will know that we called `notify_one`. After `runGC` has checked `_canContinueGC`, it resets it to `false`.
You can easily reproduce the deadlock with this code:
```cpp
int port = …
```
> Prevent deadlock when the server is stopping

- ixwebsocket/IXNetSystem.h
Fix to build under FreeBSD 13.1. `<sys/types.h>` was needed.
Built with Clang 13.0.0. There are still some warnings: 1x `-Wdeprecated-copy` 3x `-Wunused-parameter` 1x `-Wreorder-ctor`
built with `cmake -B build -DCMAKE_BUILD_TYPE=debug -DUSE_TEST=1` from project root on `master` branch
tested with `ctest` in ./build
```
Test project /root/IXWebSocket/build/test
Start  1: IXSocketTest
1/16 Test  #1: IXSocketTest .................................   Passed    0.02 sec
Start  2: IXSocketConnectTest
2/16 Test  #2: IXSocketConnectTest ..........................   Passed    0.02 sec
Start  3: IXWebSocketServerTest
3/16 Test  #3: IXWebSocketServerTest ........................   Passed    4.92 sec
Start  4: IXWebSocketTestConnectionDisconnection
4/16 Test  #4: …
```
> Build fix for FreeBSD

- ixwebsocket/IXWebSocketTransport.cpp
- test/CMakeLists.txt
closes #417
to re-summarize:
if a websocket server sends a close and immediately drops the connection, then ixwebsocket will close with "1011 Internal error" since it fails to reply with a close frame of its own. im not super sure how the connection is closing that causes it to error and im struggling to replicate it myself, but the code in the issue still causes it. [this](https://github.com/openssl/openssl/blob/19cc035b6c6f2283573d29c7ea7f7d675cf750ce/ssl/record/rec_layer_s3.c#L320-L321) is where openssl errors, but it happens with mbedtls as well
https://github.com/machinezone/IXWebSocket/blob/dc7b986e1092e59195085b708033723f4912b98f/ixwebsocket/IXWebSocketTransport.cpp#L699-L709
https://github.com/machinezone/IXWebSocket/blob/dc7b986e1092e59195085b708033723f4912b98f/ixwebsocket/IXWebSo …
> fix incorrect closures with code 1011 Internal error

- ixwebsocket/IXSocketMbedTLS.cpp
I am a maintainer of vcpkg, and when I updated `ixwebsocket` to version 11.4.4, I encountered the following errors:
```
\ixwebsocket\IXSocketMbedTLS.cpp(61): error C2065: 'errorMsg': undeclared identifier
\ixwebsocket\IXSocketMbedTLS.cpp(62): error C2065: 'errorMsg': undeclared identifier
\ixwebsocket\IXSocketMbedTLS.cpp(88): error C2065: 'errorMsg': undeclared identifier
```
Above errors occurred because `errorMsg` was commented out in PR https://github.com/machinezone/IXWebSocket/pull/399, I don't know why it was commented out.
To fix this issue, I uncomment the codes.
> Fix error C2065: 'errorMsg': undeclared identifier

- ixwebsocket/IXWebSocket.cpp
- ixwebsocket/IXWebSocket.h
- ixwebsocket/IXWebSocketServer.cpp
setThreadName in WebSocket::run will overwrite the previously set Srv::ws:, and getUrl is empty at this time, resulting in an empty thread name. For the client, 16 characters are not enough to represent very valid information in Linux. So delete setThreadName in WebSocket::run
> Fix server empty thread name

- ixwebsocket/IXDNSLookup.cpp
- ixwebsocket/IXNetSystem.cpp
- ixwebsocket/IXSocketOpenSSL.cpp
When using the compiler options -Wall and -Werror, warnings caused by type mismatches are treated as errors, leading to compilation failure.
> Fix MinGW build warning

- ixwebsocket/IXHttpServer.cpp
- test/IXHttpServerTest.cpp
Not sure why it was copying request headers to the response so I took that out altogether.   Response headers should be determined by the server and not parroted from the client.   For example, Accept-Encoding and Content-Encoding should be set by the server and not the client as it was before.  With removal of the blind copy of request headers, I added explicit setting of Content-Encoding for the gzip ifdef case and added a test to verify it was set.
> Fix #286 - http response headers overwritten with request headers

- ixwebsocket/IXWebSocketTransport.cpp
This might happen in some special cases where `WebSocketTransport::sendOnSocket()` fails, closes the socket, and set the ready state to CLOSED, but `WebSocket::run()` stills wait the interrupt event to happen.
Possibly related to #474.
> Fix hanging of WebSocket::stop() waiting for its thread to join

- README.md
Some of the information in the README is outdated and some of the links are broken (or point to links that have been since moved elsewhere). This PR just updates the README to clean it up a bit.
> Fix links & update info in README

- ixwebsocket/IXHttp.cpp
IXWebSocket needs exceptions support because of the use of stoi. In order to build when cpp exceptions are disabled, we can use strtol.
> allow building when cpp exceptions are disabled

- ixwebsocket/IXWebSocketProxyServer.cpp
Since factory returns a ProxyConnectionState, setOnConnectionCallback will be a ProxyConnectionState. The code already makes that assumption, since it does not check of state return value. Using a static_pointer_cast will allow the library to be build with rtti.
> Allow building without rtti

- ixwebsocket/IXSocketOpenSSL.cpp
> Fix for C++/WinRT compile issue

- ixwebsocket/IXSocketMbedTLS.cpp
Currently, the code spikes the CPU to 100% while waiting to receive a message on a broken connection when using MBedTLS.  It fails to detect the broken connection.  This pull request fixes that.
> Fix MbedTLS disconnect handling.

- ixwebsocket/IXSelectInterruptPipe.cpp
Valgrind keeps complaining that close() on the invalid descriptor -1 is happening here. I suppose that close shouldn't be called when the descriptor value is known to be invalid. It's not a fatal error or something, but this practice is able to create a lot of flood in the logs.
> Don't call close() on -1.

- ixwebsocket/IXUrlParser.cpp
- test/IXUrlParserTest.cpp
A URL such wss://google.com?arg=value&arg2=value2 is also valid, this PR adds support for it
> Support URLs with no slash before the question mark

- CMakeLists.txt
397bb5d18a6fa5c37cf999339959efa1f58080c3 introduced a bug by using `CMAKE_PROJECT_VERSION`. While a valid variable, to [quote the documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_PROJECT_VERSION.html),
> This variable holds the version of the project as specified **in the top level CMakeLists.txt** file by a [project()](https://cmake.org/cmake/help/latest/command/project.html#command:project) command
This is a problem if using IXWebSocket as a submodule, as IXWebSocket is no longer the top-level project in this scenario. Best-case, the version for the resulting shared library is wrong. Worst-case, which happened to a project of mine, no version is defined, and everything explodes. Because the variable is then interpreted to be empty, a `set_target_properties` call …
> Fix bad version variable

- README.md
- ixwebsocket/IXSocketMbedTLS.cpp
I have an emulator that makes use of IXWebSocket for networking under the hood [here](https://github.com/itgmania/itgmania).
When updating to the latest MbedTLS 3.6.0 LTS, I noticed that our SSL requests started failing, while non-SSL requests were still fine. After some digging, it seems like calling `psa_crypto_init()` somewhere in the code allowed it to start working again, which is what this PR suggests.
In the MbedTLS codebase ([here](https://github.com/Mbed-TLS/mbedtls/blob/development/docs/use-psa-crypto.md)), it says that by using `MBEDTLS_USE_PSA_CRYPTO` we promise to also call `psa_crypto_init()` before calling any PK, X.509 or TLS functions, so we control that using a compile time definition named `IXWEBSOCKET_MBEDTLS_USE_PSA_CRYPTO`.
> Initialize the PSA Crypto API if requested

- ixwebsocket/IXDNSLookup.cpp
- ixwebsocket/IXSetThreadName.cpp
With these, it builds on Tiger.
> Minor fixes for < 10.6

- ixwebsocket/IXSocket.h
Fixes an error with undefined `ssize_t`
> IXSocket.h: add missing <sys/types.h> for macOS

- ixwebsocket/IXSocketMbedTLS.cpp
This PR removes the define introduced in https://github.com/machinezone/IXWebSocket/pull/514, in favor of just version checking the MbedTLS (defined [here](https://github.com/Mbed-TLS/mbedtls/blob/0e7aaae1fd9b2bb3801bc7839da063e2abb8253b/include/mbedtls/build_info.h#L27-L29)). I think this implementation is more portable as any projects dependent on this change can get it immediately when updating their MbedTLS library, instead of manually adding in a new define.
--------------------
It looks like brew updated their mbedtls version 2 months ago as per [this link](https://github.com/Homebrew/homebrew-core/commit/54c3c7c0f6cb42efc5fbd6a95afb62fba133c8c0).
This update happened on March 28th, while the last IXWebSocket update before this changed happened one day earlier on [March …
> Version check MbedTLS instead of introducing a new define when initializing PSA Crypto API

- ixwebsocket/IXSocketMbedTLS.cpp
Hello (and thanks for this library!), I've found two leaks when using sockets with SSL/TLS and MbedTLS.
One leak about the key, and one from the new PSA layer introduced with MbedTLS 3.6.0.
The leaks are detected on Windows with VLD and on Linux with ASAN.
> Fix memory leaks in SocketMbedTLS when closing.

- ixwebsocket/IXWebSocketHandshake.cpp
- test/CMakeLists.txt
- test/IXWebSocketHostTest.cpp
I had a situation with a thirdparty websocket server which was rejecting the upgrade to a websocket connection (in `IXWebSocketHandshake::clientHandshake(...)`) with a HTTP 400 (Bad Request) error because the thirdparty server didn't like the format of the "Host:" header being set to "stream.example.com:port", so, e.g.
```
GET /required/path HTTP:/1.1
Host: stream.example.com:1234
```
Failed with a HTTP 400 error code (when IXWebSocket expects a HTTP 101 Switching Protocols code), but the following without ":port":
```
GET /required/path HTTP:/1.1
Host: stream.example.com
```
Worked OK.
This small change allows the "Host" header to be specified in `ix::WebSocketHttpHeaders", e.g.
```
ix::WebSocket webSocket{};
ix::WebSocketHttpHeaders headers{};
headers["Host"] = "stream.example.com"; …
```
> Allow Host to be overridden in handshake headers

- ixwebsocket/IXHttp.cpp
Heyo,
Thank you for the awesome library!
I fixed a mildly annoying compiler warning by making this a static cast instead of an implicit one.
I also rearranged some of the checks to add better error messages to the 'Content-Length' header check overall.
First ever contribution to a public repo, let me know if it checks out!
> Fix: 'Content-Length' header check implicit cast

- third_party/msgpack11/msgpack11.hpp
cstdint needs to be included explicitly since GCC 15.
https://gcc.gnu.org/gcc-15/porting_to.html
Downstream bug: https://bugs.gentoo.org/937500
```
$ cmake -B build -DUSE_WS=ON -DCMAKE_DISABLE_PRECOMPILE_HEADERS=OFF
$ cmake --build build
[ 93%] Building CXX object ws/CMakeFiles/ws.dir/__/third_party/msgpack11/msgpack11.cpp.o
In file included from /IXWebSocket/third_party/msgpack11/msgpack11.cpp:1:
/IXWebSocket/third_party/msgpack11/msgpack11.hpp:53:25: error: 'uint8_t' was not declared in this scope
53 |     typedef std::vector<uint8_t> binary;
|                         ^~~~~~~
```
> Include cstdint for compatibility with GCC 15

- ixwebsocket/IXWebSocketTransport.cpp
- ixwebsocket/IXWebSocketTransport.h
When setReadyState(CLOSED) is executed from two different threads (the server's thread, detecting a close trying to receive and a separate sending thread), there is a race where both see _readyState as non-CLOSED and both execute the _onCloseCallback().  Worse, the server's thread might be returning from ->run(), unsetting the callback, while the other thread is still about to call the _onCloseCallback(), resulting in a crash rather than "just" a duplicate invocation.
This change ensures that setReadyState() *and* the_onCloseCallback() are executed by a single thread till completion.
I was tempted to remove the std::atomic<> for _readyState, but left it assuming it's still good having for getReadyState().
I've first tried _readyState.exchange() which seemed promising, but still crashed …
> IXWebSocketTransport::setReadyState(): Run under lock

- ixwebsocket/IXWebSocketTransport.cpp
- ixwebsocket/IXWebSocketTransport.h
Buffering too much data into _rxbuf results in dispatch() processing to run into a performance issue due to calling _rxbuf.erase() for each frame.
Concretely, if _rxbuf grows large due to a client sending frames very fast, each processing in dispatch() results in moving the remaining buffer to the front.
Instead of restructuring to avoid .erase(), this patch limits the maximum size of _rxbuf to kChunkSize to alleviate the O^2 erase() overhead. It also has the side-effect of keeping the received data in the OS's TCP stack, building up back pressure to the client earlier if the server code can't keep up.
Fixes #429
> IXWebSocketTransport: Avoid bloating _rxbuf

- ixwebsocket/IXNetSystem.cpp
According to the method mentioned by [engun](https://github.com/engun) in #474, this PR fixes no callback called when the server is disconnected on windows system. In addition, There may be the same issue in #396, #469.
> Fix no callback when the server is disconnected on windows

- docs/build.md
- tools/build_android.sh
- tools/build_ios.sh
Opening this PR to document my findings and close #546. Adding a script for building a static lib for ios, some minor changes to the build_android.sh script to make usage of it clearer and adding to the build documentation.
> Improve documentation and add an ios build script
